language: php
dist: trusty

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - LARAVEL_VERSION=">=5.4.0 <5.4.20"
  - LARAVEL_VERSION=">=5.4.20 <5.5.0"
  - LARAVEL_VERSION="5.5.*"
  - LARAVEL_VERSION="5.6.*"
  - LUMEN_VERSION="5.4.*"
  - LUMEN_VERSION="5.5.*"
  - LUMEN_VERSION="5.6.*"

matrix:
  exclude:
    - php: 5.6
      env: LARAVEL_VERSION="5.5.*"
    - php: 5.6
      env: LUMEN_VERSION="5.5.*"
    - php: 5.6
      env: LARAVEL_VERSION="5.6.*"
    - php: 5.6
      env: LUMEN_VERSION="5.6.*"
    - php: 7.0
      env: LARAVEL_VERSION="5.6.*"
    - php: 7.0
      env: LUMEN_VERSION="5.6.*"

before_install:
  - if [ -n "$LARAVEL_VERSION" ]; then composer remove --dev --no-update "laravel/lumen-framework"; fi
  - if [ -n "$LARAVEL_VERSION" ]; then composer require --no-update "laravel/framework:$LARAVEL_VERSION"; fi
  - if [ -n "$LUMEN_VERSION" ]; then composer remove --dev --no-update "laravel/framework"; fi
  - if [ -n "$LUMEN_VERSION" ]; then composer require --no-update "laravel/lumen-framework:$LUMEN_VERSION"; fi

install: composer install --prefer-dist --no-interaction --no-suggest

before_script: SUPERVISE=no ./start-cluster.sh || { cat ./cluster/*.log; false; }

script: vendor/bin/phpunit ${LUMEN_VERSION:+--exclude-group laravel-only}
